// api/analyze.js
export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).send('Method Not Allowed');

  try {
    const { image } = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    const apiKey = process.env.GEMINI_API_KEY;
    
    // Using Gemini 1.5 Flash for faster and cost-effective analysis
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(apiUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        contents: [{
          parts: [
            { 
              text: "ACT AS A PRECISE MEASUREMENT TOOL. Analyze the foot size relative to the A4 paper (21.0cm x 29.7cm). Establish a pixel-to-cm ratio. Measure length from heel to longest toe and return ONLY a JSON: {'eu': XX, 'cm': XX.X, 'us': XX, 'uk': XX, 'width': 'XX cm', 'match_confidence': 'XX%'}. No markdown, no conversational text." 
            },
            { 
              inline_data: { 
                mime_type: "image/jpeg", 
                data: image.split(',')[1] 
              } 
            }
          ]
        }]
      })
    });

    const data = await response.json();
    
    if (data.error) {
       return res.status(500).json({ error: data.error.message });
    }

    // Extract text from Gemini response
    const textResult = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!textResult) {
      return res.status(500).json({ error: "No analysis generated by AI." });
    }

    // Clean up potential markdown and parse JSON
    const cleanJson = textResult.replace(/```json|```/g, "").trim();
    const resultObject = JSON.parse(cleanJson);
    
    return res.status(200).json(resultObject);
  } catch (error) {
    console.error("Gemini API Error:", error);
    return res.status(500).json({ error: "Analysis failed: " + error.message });
  }
}
